---
- name: Fail when 'aws_s3backend_iam_name' is undefined
  ansible.builtin.fail:
    msg: "'aws_s3backend_iam_name' is required when 'aws_s3backend_iam_type' is provided."
  when:
    - aws_s3backend_iam_name is undefined
    - aws_s3backend_iam_type is defined

- name: Create S3 bucket with versioning enabled
  amazon.aws.s3_bucket:
    name: "{{ aws_s3backend_bucket_name }}"
    state: present
    versioning: true

- name: Create dynamodb table
  community.aws.dynamodb_table:
    state: present
    name: "{{ aws_s3backend_dynamodb_table_name }}"
    hash_key_name: "LockID"
    hash_key_type: "STRING"
    wait: true
    table_class: 'STANDARD'
  when: aws_s3backend_dynamodb_table_name is defined

- name: Apply policy to user/role/group
  amazon.aws.iam_policy:
    iam_type: "{{ aws_s3backend_iam_type }}"
    iam_name: "{{ aws_s3backend_iam_name }}"
    policy_name: "{{ aws_s3backend_policy_name }}"
    policy_json: "{{ lookup('template', 'policy.json.j2') }}"
    state: present
  when: aws_s3backend_iam_type is defined
