name: Sanity
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - stable-*
    tags:
      - '*'

jobs:
  sanity:
    uses: ansible-network/github_actions/.github/workflows/sanity.yml@main
